### ISSUE TITLE
Problems in the Examples

### ISSUE THREAD

**Issue by LoyTakian** [alpinestudios/oogabooga#12]
Hey! I'm new here and after going through the "Development environment setup" class, I tried to run the example games from the `examples` folder but I had problems with the some of them.
After I tried running them the first time, the `tile_game.c` log message suggested me to install the "Graphics Tools" feature on my PC, so I did, restarted the PC and tried running all of them again.
The screenshots are [here](https://imgur.com/a/VFpsCkm)

**The results are**:
* Examples from the lines 36, 38, 39 and 44 worked fine;
* Example from line 41 just give me an empty blue screen, I tried clicking and WASD keys but nothing happened;
* Examples from line 40, 42 and 43 start blank screens, log error messages and then closes themselves after a 2~ seconds;

**How I ran them**:
In the `build.c` I uncommented each line I was testing at the moment and commented the rest, then saved the file and ran the "Run Build Task" option, went into the build folder and executed the file cmake.exe from there.

**Additional details**:
I also tried moving the local repository into a different disk, tried running the vscode as admin and tried to run the `build.bat` file from file explorer itself, as well as running the cgame.exe as admin, but nothing changed.
My PC details:
![image_2024-08-10_214813233](https://github.com/user-attachments/assets/a0f80877-c2ab-4f8f-a5ed-d750b030426d)

**Comment by asbott** [comment]
Its looking for files in the relative directory "oogabooga/examples/....."
So the workspace directory needs to be one above "oogabooga" i.e. your project room directory. It looks like you are running the executable with a different workspace directory (maybe you are in build/ ?)
