### ISSUE TITLE
Can't run build.bat

### ISSUE THREAD

**Issue by TobiasBms** [alpinestudios/oogabooga#14]
Howdy!

When I run build.bat I get the following error:

https://pastebin.com/tm7DwJEn

I have install the windows sdk msys2  and installed the plugins needed ( I think ) 

I have the following cpu. Processor. Intel(R) Core(TM) i5-10400F

I am fairly new to C, so I am abit unsure what to do at this point.

**Comment by asbott** [comment]
Oogabooga is not tested and won't work well with unix emulation tools thingys (or whatever you wanna call them: cygwin, mingw, msys). You should install LLVM and compile with the clang binary in `LLVM/bin`.

Make sure `LLVM/bin` is added to PATH *BEFORE* anything else that contains a clang binary.

Will maybe fix this at some point but we're solely targetting windows at the moment so it's not really a priority.

**Comment by Finxx1** [comment]
Adding `-Xclang -target-feature -Xclang +amx-int8` to the command line flags appeared to fix the problem for me.

**Comment by Ip-bruce** [comment]
"Make sure LLVM/bin is added to PATH BEFORE anything else that contains a clang binary." How can i do that?

**Comment by Finxx1** [comment]
When installing LLVM (currently [18.1.8](https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.8)) make sure Add LLVM to the system PATH for current user (or all users if you want) is selected.
![image](https://github.com/user-attachments/assets/682295e1-1785-4fb4-87e7-004db0bb680f)

**Comment by Ip-bruce** [comment]
Thanks @Finxx1, I had installed for all users, I tried  reinstalling for the current user but the error persists.
 But about this command line "-Xclang -target-feature -Xclang +amx-int8" where exactly I can put it ?

**Comment by Finxx1** [comment]
You can put it at the end of the line in build.bat starting with `clang`. However, if you are using the LLVM installer, you shouldn't get the error. Is it the same error in this issue? If not, you should open a new issue for that error.

For reference, the error in this issue is this:
```
error: always_inline function '_tile_loadd_internal' requires target feature 'amx-int8', but would be inlined into function '__tile_loadd' that is compiled without support for 'amx-int8'
```

**Comment by asbott** [comment]
> "Make sure LLVM/bin is added to PATH BEFORE anything else that contains a clang binary." How can i do that?

You should go to *environment variables* on your windows system and edit the PATH variable.

**Comment by Ip-bruce** [comment]
I get rid of the first error, but I still got two more.
![image](https://github.com/user-attachments/assets/2eea560c-c0a0-41e9-b552-d0a6d1b214dd)

**Comment by lmcr666** [comment]
i also got this issue and am using windows with clang. Was following oogabooga tutorial, the Caveman C fundamentals.
wasnt able to run the project straight after forking, exactly as was done in the tutorial. got the following error:
`always_inline function '_tile_loadd_internal' requires target feature 'amx-int8', but would be inlined into function '__tile_loadd' that is compiled without support for 'amx-int8'`

i then added `-Xclang +amx-int8` to the end of the build.bat file and got the following linker errors instead:
`lld-link: error: undefined symbol: entry
>>> referenced by <location>\oogabooga\oogabooga\oogabooga.c:468
>>>               C:\Users\<user>\AppData\Local\Temp\build-5701ea.o:(main)
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

tried with -v and got nothing different, tried looking for the file referenced (` C:\Users\<user>\AppData\Local\Temp\build-5701ea.o`) assuming it would be a log file or something to get any clue on the error but it didnt even exist.

just wanted to make a game :c

**Comment by asbott** [comment]
> i also got this issue and am using windows with clang. Was following oogabooga tutorial, the Caveman C fundamentals. wasnt able to run the project straight after forking, exactly as was done in the tutorial. got the following error: `always_inline function '_tile_loadd_internal' requires target feature 'amx-int8', but would be inlined into function '__tile_loadd' that is compiled without support for 'amx-int8'`
> 
> i then added `-Xclang +amx-int8` to the end of the build.bat file and got the following linker errors instead:
> 
> ```
> lld-link: error: undefined symbol: entry
> />/>/> referenced by <location>\oogabooga\oogabooga\oogabooga.c:468
> />/>/>               C:\Users\<user>\AppData\Local\Temp\build-5701ea.o:(main)
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> tried with -v and got nothing different, tried looking for the file referenced (` C:\Users\<user>\AppData\Local\Temp\build-5701ea.o`) assuming it would be a log file or something to get any clue on the error but it didnt even exist.
> 
> just wanted to make a game :c

Have you defined entry?

**Comment by lmcr666** [comment]
that's in the oogabooga files, should I even mess with them?

**Comment by asbott** [comment]
> that's in the oogabooga files, should I even mess with them?

You define the entry function in your code. See the examples in oogabooga/examples.

**Comment by lmcr666** [comment]
your right, that worked for me
