### ISSUE TITLE
Error Running  "Build task" 

### ISSUE THREAD

**Issue by Ip-bruce** [alpinestudios/oogabooga#15]
After installing everything, at the step n° 8, Vscode return these errors:
 *  Executing task: G:\GitHub\Infectus_ogaboga\build 

In file included from ../build.c:28:
In file included from ../oogabooga/oogabooga.c:126:
In file included from C:/mingw64/lib/clang/15.0.7/include/immintrin.h:506:
C:/mingw64/lib/clang/15.0.7/include/amxintrin.h:319:15: error: always_inline function '_tile_loadd_internal'
      requires target feature 'amx-int8', but would be inlined into function '__tile_loadd' that is compiled
      without support for 'amx-int8'
  dst->tile = _tile_loadd_internal(dst->row, dst->col, base, stride);
              ^
In file included from ../build.c:28:
In file included from ../oogabooga/oogabooga.c:330:
../oogabooga/os_impl_windows.c:175:10: error: expected expression
                bool is_repeat = (lparam & 0x40000000) != 0;
                ^
../oogabooga/os_impl_windows.c:177:14: error: use of undeclared identifier 'is_repeat'
                if (is_repeat) win32_handle_key_repeat(os_key_to_key_code((void*)wparam));
                    ^
../oogabooga/os_impl_windows.c:363:2: warning: call to undeclared function 'SetProcessDpiAwarenessContext'; ISO
      C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);
        ^
../oogabooga/os_impl_windows.c:1711:13: warning: call to undeclared function 'GetDpiForWindow'; ISO C99 and
      later do not support implicit function declarations [-Wimplicit-function-declaration]
        UINT dpi = GetDpiForWindow(window._os_handle);
                   ^
2 warnings and 3 errors generated.
 *  Terminal will be reused by tasks, press any key to close it. 
![imagem_2024-08-12_195153924](https://github.com/user-attachments/assets/a54f5fc5-c7cb-42e0-8c91-a7712a4e832d)

**Comment by asbott** [comment]
See #14
