### ISSUE TITLE
Change default branch name

### ISSUE THREAD

**Issue by Krymancer** [alpinestudios/oogabooga#16]
The [default github branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches#about-the-default-branch) is now `main`, is there any plans to rename the `master` to `main`. 

I don't really mind, but it's almost a convention now, that why I asked.

**Comment by asbott** [comment]
While I'm thankful you took the time to give your thoughts, I tend not to spend brain energy on considering things that don't matter at all, so it will remain `master`. Unless you have a reason for how it actually helps effectively solve any of the problems that oogabooga as a library sets out to solve for game programmers.
