### ISSUE TITLE
math.h file not found

### ISSUE THREAD

**Issue by 102roclo** [alpinestudios/oogabooga#24]
This message happens when i try to "Run Build Task", also it doesn´t create the game executable, only the folder
In file included from ../build.c:28:
..\oogabooga/oogabooga.c:125:10: fatal error: 'math.h' file not found
  125 | #include <math.h>
      |          ^~~~~~~~
1 error generated.

**Comment by Finxx1** [comment]
There is an error in your build system. This will happen if you install LLVM/Clang without also installing Visual Studio. This problem should resolve itself if you install Visual Studio, open the developer command prompt, and then build the project.

**Comment by 102roclo** [comment]
Well I had to reinstall everything on C: for it to work but now it does! Thank you for the help
![image](https://github.com/user-attachments/assets/c18939ff-bc83-431e-bc91-dce612523d1b)
