### ISSUE TITLE
Sprite problem when changing window size

### ISSUE THREAD

**Issue by Flynnvolt** [alpinestudios/oogabooga#25]
I tried to make my window bigger and now my sprites are scuffed.

changing:

window.scaled_width = 1280;
window.scaled_height = 720;

to:

window.scaled_width = 1920;
window.scaled_height = 1080;

broke my sprites

some of the top pixel on my character is cut off and my diamond sprite is cut off on the top and has extra on the bottom.

repo:
https://github.com/Flynnvolt/TowerOfTheSky

I added a stripped down game file called "MinimalFileForTesting.c" that can be turned on in build.c for testing.

**Comment by asbott** [comment]
The sprites look normal for me. Are you using multiple monitors?

**Comment by Flynnvolt** [comment]
> The sprites look normal for me.
> 
> Are you using multiple monitors?
> 
> Are you doing system scaling?
> 
> What is your monitor resolution?

I have two montiors:
![monitors](https://github.com/user-attachments/assets/161815ca-495c-4dc0-bb8b-171fe69febb4)

one is 1920 x 1080 other one is 1680 x 1050

**Comment by Flynnvolt** [comment]
> The sprites look normal for me.
> 
> Are you using multiple monitors?
> 
> Are you doing system scaling?
> 
> What is your monitor resolution?

Can you explain what "Are you doing system scaling?" is ?

**Comment by asbott** [comment]
> > The sprites look normal for me.
> > Are you using multiple monitors?
> > Are you doing system scaling?
> > What is your monitor resolution?
> 
> Can you explain what "Are you doing system scaling?" is ?

![Screenshot 2024-08-29 150740](https://github.com/user-attachments/assets/9af5330b-b3f5-48bd-a622-d1c836f01d31)

**Comment by asbott** [comment]
> > > > The sprites look normal for me.
> > > > Are you using multiple monitors?
> > > > Are you doing system scaling?
> > > > What is your monitor resolution?
> > > 
> > > 
> > > Can you explain what "Are you doing system scaling?" is ?
> > 
> > 
> > ![Screenshot 2024-08-29 150740](https://private-user-images.githubusercontent.com/66182434/362698040-9af5330b-b3f5-48bd-a622-d1c836f01d31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MzcyMTksIm5iZiI6MTcyNDkzNjkxOSwicGF0aCI6Ii82NjE4MjQzNC8zNjI2OTgwNDAtOWFmNTMzMGItYjNmNS00OGJkLWE2MjItZDFjODM2ZjAxZDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEzMDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZjkzOGZjYWFlNTRjYTExYjI0YWM2NzYyNTc5MDg1Yzg1NzM2MmQ5YmE3MGM2MjZmNmUyZTg0ZmI2ZDczMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XGTHN5kY0zu968B0EH7MgMhTNQNrFVq-dZmIZjMVClE)
> 
> ![image](https://private-user-images.githubusercontent.com/105185949/362699221-1ecb1ea4-03d1-4ed5-a420-9611f7d73fe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDk5MDIsIm5iZiI6MTcyNDk0OTYwMiwicGF0aCI6Ii8xMDUxODU5NDkvMzYyNjk5MjIxLTFlY2IxZWE0LTAzZDEtNGVkNS1hNDIwLTk2MTFmN2Q3M2ZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxNjQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzQxMDFhNjdhZDc3ZTIwNTRhNTcwNTI3ZThkMDg4NmEwNTYyMzQwNmI2ODViZTNiNjU5ZDc4NjNmYjNmYjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qIfLrBGugcXSs4leQY2yfiu_oghgC2z4FGo3cdQIWvU)
> 
> ![image](https://private-user-images.githubusercontent.com/105185949/362699298-347160aa-8190-4d71-8e0d-2ecc620c97fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDk5MDIsIm5iZiI6MTcyNDk0OTYwMiwicGF0aCI6Ii8xMDUxODU5NDkvMzYyNjk5Mjk4LTM0NzE2MGFhLTgxOTAtNGQ3MS04ZTBkLTJlY2M2MjBjOTdmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxNjQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGE0NTQzYWUzMjQ3MGE2ZGQyNzZkZDJlNTgzZDk5MGEyMmJiZTdjYzdiOGE3OThkNGNhYzQyZDkyZGVmNzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c_wkABr6HoovS10IlGCxvBAS42Z9qJx5-Ex6NoIMSIs) i guess i am should I turn it off?

No you shouldn't need to change anything, I'm just wondering if that might be causing issues in oogabooga. But 100% is the default.

Actually, I think it's a problem with the texture sampling when the window is uneven. I tried to fix this before and thought I figured it out but apparently not. (When you set height to 1080, it will shrink it to fit with the taskbar when not in fullscreen, so it gets set to 1047). 

I will make the window size just always round to the next multiple of 2 for now, which should solve your problem with the next update. Feel free to reopen this if your problem isn't solved with the next update (0.01.007).
