### ISSUE TITLE
VERTEX_2D_USER_DATA_COUNT naming

### ISSUE THREAD

**Issue by bigrando420** [alpinestudios/oogabooga#28]
`VERTEX_2D_USER_DATA_COUNT` naming is a bit confusing with the '2D' in there, not exactly sure what it means?

I gathered this define was driving the array count of the Vector4 user_data though by looking at the source. Was just confusing at first glance though.

Not at all an important issue, just thought I'd share my thought process.

**Comment by asbott** [comment]
i wopsie, i fixy smixy
