### ISSUE TITLE
merging from upstream fork is high friction

### ISSUE THREAD

**Issue by bigrando420** [alpinestudios/oogabooga#29]
It seems like every time I go to merge from the upstream fork it's taking longer and longer, with a shit load of dealing with the same conflicts over and over.

It's probs due to my lack of experience with this, but if I'm struggling, I'm sure other people are as well.

I wonder if we can restructure things to not be a fork?

More like just download the zip of the latest release, and copy across the folders. Then you're good to go.

It would be a big win in reducing update friction.

**Comment by bigrando420** [comment]
Actually I just updated by doing exactly this, and it works fine. Should probs update the course to reflect this new method instead of trying to wrangle with an upstream merge.

copied oogabooga folder + build.c across: https://github.com/bigrando420/game1/commit/dc87c45ac54565d6a2cd4dc099a31b3316aea553
fixed errors: https://github.com/bigrando420/game1/commit/a2ad98cc2cc8d387a689cbf79ef1a6c79f94dd3a

the only big friction point here was copying across the new build.c changes and getting my modifications merged back in.
same with the build.bat (although no new changes, I still had to look to see if there was any additions).

seems a lot easier than the upstream merge anyway.

**Comment by asbott** [comment]
Where are the conflicts? I feel like as long as you don't modify stuff in oogabooga/ then the only conflict should be build.c since the example includes change slightly.

**Comment by bigrando420** [comment]
yeah just build.c

but for some reason it keeps getting me to fix conflict after conflict _within_ build.c

no clue why, but I have to keep running through all the conflicts since the first init commit, like 10 times at different points in the history

**Comment by asbott** [comment]
You can hard reset to latest commit:

https://chatgpt.com/share/944e068b-3768-448b-8f2a-9bfcd6e9d083
