### ISSUE TITLE
Compile the engine without windowing and graphics?

### ISSUE THREAD

**Issue by cozis** [alpinestudios/oogabooga#3]
Hello! I'm trying to make a multiplayer game with this engine and I'm looking for the best way to get a headless build of the game to run on servers. The idea is that regular builds of the game would only run on windows, while headless builds (no windowing, no graphics) should run on both windows and linux. 

The two solutions I can think of are:
1. Only use the engine for builds with graphics
2. Exclude graphics and windowing from headless builds of the engine and port the rest to linux

At the moment I went with (1), but the ideal solution for me would be something similar to (2).

I wanted to get your thoughts before doing any significant changes to the engine

**Comment by asbott** [comment]
Interesting, I haven't considered this scenario.

What parts of the engine do you need for the server?

**Comment by cozis** [comment]
I'm guessing everything except windows, rendering and audio. You could think of the server as a CLI app

**Comment by asbott** [comment]
We could do something like a `#define OOGABOOGA_HEADLESS 1` which #if removes the gfx_init call and most of os_init (Windowing & Audio stuff)

**Comment by asbott** [comment]
Although since we don't have linux implementations, maybe you're thinking about just stripping the whole os thing and programming directly in unix ? `#define OOGABOOGA_NO_OS_IMPLEMENTATION 1` ?

**Comment by cozis** [comment]
Something like `OOGABOOGA_NO_OS_IMPLEMENTATION` works. Since I'd be porting code anyways I wouldn't mind contributing code back to the engine if that's of interest

**Comment by asbott** [comment]
> Something like `OOGABOOGA_NO_OS_IMPLEMENTATION` works. Since I'd be porting code anyways I wouldn't mind contributing code back to the engine if that's of interest

Yeah go for it, let me know if something is confusing in there

**Comment by cozis** [comment]
I'll start by adding the `OOGABOOGA_HEADLESS` option then

**Comment by cozis** [comment]
One last thing. Any preferences/conventions for commits and PRs?

**Comment by asbott** [comment]
Not really, do as you like.
